defaults:
  - base_dataset
  - view_sampler: bounded

name: scannet
roots: [datasets/scannet_test]
make_baseline_1: true
augment: true

input_image_shape: [256, 256]
original_image_shape: [256, 256]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 120.0

skip_bad_shape: false
